version: "3.3"

services:
  openhab2:
    image: openhab/openhab
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /share/ContainerData/openhab2/openhab/conf:/openhab/conf
      - /share/ContainerData/openhab2/openhab/userdata:/openhab/userdata
      - /share/ContainerData/openhab2/openhab/addons:/openhab/addons
    ports:
      - "8082:8080"
    environment:
      TZ: "Europe/Warsaw"
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Warsaw"
