version: "3"

build:
  context: .
  args:
    local_folder: /ContainerData/openhab2

services:
  openhab2:
    container_name: openhab2
    image: openhab/openhab
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${local_folder}/openhab/conf:/openhab/conf
      - ${local_folder}/openhab/userdata:/openhab/userdata
      - ${local_folder}/openhab/addons:/openhab/addons
    ports:
      - "8082:8080"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Warsaw"
